### ISSUE TITLE
glitch

### ISSUE THREAD

**Issue by Realswitzer** [OGBlooketCheater/Blooket-Cheaters-Menu#3]

**Comment by OGBlooketCheater** [comment]
WDYM

**Comment by OGBlooketCheater** [comment]
MInesraft got taken down

**Comment by dudecrystal** [comment]
> MInesraft got taken down

are you minesraft? alt acc? if so how do i do it if i copy all code it dont work.

**Comment by Realswitzer** [comment]
> > MInesraft got taken down
> 
> are you minesraft? alt acc? if so how do i do it if i copy all code it dont work.

no, ogblooketcheater is a skid and not minesraft nor affiliated with minesraft.
minesraft, until he gets unsuspended, is using MllereA
use https://github.com/VillainsRule/Blooket-Site

**Comment by OGBlooketCheater** [comment]
> you literally skidded it.
> 
> > Please DO NOT Recreate This Or Steal Code!
> > You Can Fork It But DO NOT Copy and Paste And Paste Code
> > And Call It Your Own
> 
> [README](https://github.com/OGBlooketCheater/Blooket-Cheaters-Menu/blob/main/README) you didn't make this. you are copying someone elses work, and are seemingly pass it off as your own (no credit appears given at face value).
> 
> it resembles aerell's repository with the obfuscated folder and gui.js/mobilegui.js.
> 
> > MInesraft got taken down
> 
> i fail to see how aerell's repository being taken down due to an account suspension helps prove you are not a skid. despite his repository being down, [the license <archive.org>](https://web.archive.org/web/20230123145517/https://github.com/Minesraft2/Blooket-Cheats/blob/main/LICENSE)
> 
> > You may not "skid", "steal", "copy", "reproduce", "scounder", "recreate" any of the code and scripts inside of this.
> 
> due to the lack of mention of the original repository, owner, etc, it likely falls under "stealing" or "skidding".

NO CREDIT? I HAVE A DISCCLAIMER

**Comment by Realswitzer** [comment]
???
just tell them to use aerell’s repo?
why do you need to copy the source code, upload it to your repo (not even a fork), and tell people to use your repo?

**Comment by OGBlooketCheater** [comment]
> ??? just tell them to use aerell’s repo? why do you need to copy the source code, upload it to your repo (not even a fork), and tell people to use your repo?

I dont tell people to use mine, they just find it and use it.

**Comment by Realswitzer** [comment]
ok, trying to completely hide the fact you were called out

**Comment by Realswitzer** [comment]
this issue is not related to the GUI, in which case I would create the issue under Aerell’s repo. this is related to you being a scumbag.

**Comment by Realswitzer** [comment]
trying to delete everything and change the name out of nowhere isn’t a good look.

**Comment by Realswitzer** [comment]
this is still not due to a "glitch". this is you being a skid.

**Comment by Realswitzer** [comment]
this is like that book, think it’s called “nineteen eighty-four”
