### ISSUE TITLE
Realhack1 Is a IP LOGGER

### ISSUE THREAD

**Issue by Realhack1** [OGBlooketCheater/Blooket-Cheaters-Menu#6]
at  this link https://stonks.boats/CPIP7F.txt is my better hacks gui use inspect if you want to break it down into induvial hacks.
I realhack1 Give you permission for my hacks And dont ask for credits

**Comment by Realhack1** [comment]
wrong link

**Comment by OGBlooketCheater** [comment]
> at this link https://stonks.boats/CPIP7F.txt is my better hacks gui use inspect if you want to break it down into induvial hacks. I realhack1 Give you permission for my hacks And dont ask for credits

Nah

**Comment by OGBlooketCheater** [comment]
> at this link https://stonks.boats/CPIP7F.txt is my better hacks gui use inspect if you want to break it down into induvial hacks. I realhack1 Give you permission for my hacks And dont ask for credits

Nah

**Comment by OGBlooketCheater** [comment]
> https://stonks.fun/1D39KR.txt

goes to https://irunblocked.asia/

**Comment by Realhack1** [comment]
TY sir

**Comment by Realhack1** [comment]
United States, Boardman?

**Comment by OGBlooketCheater** [comment]
> United States, Boardman?

what??

**Comment by OGBlooketCheater** [comment]
> maybe

wtf is boardman anyway
i dont live there

**Comment by Realhack1** [comment]
are you sure?

**Comment by Realswitzer** [comment]
i want to note that using an ip grabber especially on a public facing site is a terrible fucking method since you know random people will just click on it
